config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :doctors do
    collection do
      get 'list_male'
      get 'list_female'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :gender, presence: true

  scope :male, -> { where(gender: 'male') }
  scope :female, -> { where(gender: 'female') }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  before_action :authenticate_user!, except: [:index]

  def show
    @doctor = Doctor.find(params[:id])
  end

  def index
    @doctors = Doctor.all
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to doctor_path
    else
      render :new
    end
  end

  def edit
    @doctor = Doctor.find(params[:id])
  end

  def update
    @doctor = Doctor.find(params[:id])
    if @doctor.update_attributes(doctor_params)
      redirect_to doctor_path(@doctor)
    else
      render :edit
    end
  end

  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy
    redirect_to doctors_path
  end

  def list_male
    @doctors = Doctor.male
  end

  def list_female
    @doctors = Doctor.female
  end

  private

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name, :address, :gender)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_for @doctor do |f| %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :address %>
  <%= f.text_area :address %>

  <%= f.label :gender %>
  <%= f.select :gender, [['Female', 'female'], ['Male', 'male']] %>

  <%= f.submit %>

<% end %>

app/views/doctors/edit.html.erb
<%= render partial: 'form' %>

app/views/doctors/index.html.erb
<table>

  <thead>

    <th>first name</th>
    <th>last name</th>
    <th>address</th>
    <th>gender</th>
    <th></th>
    <th></th>

  </thead>

  <tbody>

    <% @doctors.each do |doctor| %>

      <tr>

        <td><%= doctor.first_name %></td>
        <td><%= doctor.last_name %></td>
        <td><%= doctor.gender %></td>
        <td><%= doctor.address %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Delete', doctor_path(doctor), method: :delete %></td>

      </tr>

    <% end %>

  </tbody>

</table>

app/views/doctors/list_female.html.erb
<table>

  <thead>

    <th>first name</th>
    <th>last name</th>
    <th>address</th>
    <th>gender</th>
    <th></th>
    <th></th>

  </thead>

  <tbody>

    <% @doctors.each do |doctor| %>

      <tr>

        <td><%= doctor.first_name %></td>
        <td><%= doctor.last_name %></td>
        <td><%= doctor.gender %></td>
        <td><%= doctor.address %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Delete', doctor_path(doctor), method: :delete %></td>

      </tr>

    <% end %>

  </tbody>

</table>

app/views/doctors/list_male.html.erb
<table>

  <thead>

    <th>first name</th>
    <th>last name</th>
    <th>address</th>
    <th>gender</th>
    <th></th>
    <th></th>

  </thead>

  <tbody>

    <% @doctors.each do |doctor| %>

      <tr>

        <td><%= doctor.first_name %></td>
        <td><%= doctor.last_name %></td>
        <td><%= doctor.gender %></td>
        <td><%= doctor.address %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Delete', doctor_path(doctor), method: :delete %></td>

      </tr>

    <% end %>

  </tbody>

</table>

app/views/doctors/new.html.erb
<%= render partial: 'form' %>

app/views/doctors/show.html.erb
<%= @doctor.first_name %>
<%= @doctor.last_name %>
<%= @doctor.address %>
<%= @doctor.gender %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AcAssessmentApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>